### ISSUE TITLE
how you train the model

### ISSUE THREAD

**Issue by godpi** [Ultraleow/Masked-Face-Recognition#1]
Hello, I'm new in github and I have interest with your repository.But I have a problem that how you train the model "face_mask_detection.pb" and "weight_15.pb".Could you please tell me the details about the model training?

**Comment by leowjs** [comment]
Hi,

https://www.udemy.com/course/ai-deep-learning-facial-masked-face-detection-
recognition/
This is the tutorial I refer to when setting up to scan my face. I did not
train it, just using the pre-trained weight he provided.
You may download the course here, and the source code and weight.
https://drive.google.com/drive/u/1/folders/1Z4uAM9Fe31ga3Op4St6XNlaihOZDC69K



Best Reagrds
Leow Jun Shou

**Comment by godpi** [comment]
Thank you very much!
